### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by MiaoyunZhao** [YBZh/EFDM#2]
Hi, thanks for the impressive work. Are the pretrained model weights available for download somewhere?

**Comment by YBZh** [comment]
Thanks for your interest. The pre-trained encoder and decoder for the style transfer task can be found here: https://github.com/YBZh/EFDM/tree/main/ArbitraryStyleTransfer. For the domain generalization tasks, we do not provide pre-trained checkpoints, since there are many sub-tasks and each sub-task could be learned quickly (e.g., several hours on one GPU).
